# Generated by Django 4.2.5 on 2023-09-23 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import mptt.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True, verbose_name='Название')),
                ('slug', models.SlugField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=300, verbose_name='должность')),
                ('name_company', models.CharField(max_length=300, verbose_name='компания')),
                ('charge', models.CharField(max_length=300, verbose_name='обязанности')),
                ('start_work', models.DateField(verbose_name='начало работы')),
                ('end_work', models.DateField(verbose_name='конец работы')),
                ('stack', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='стек технологий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('theme', models.CharField(max_length=500, verbose_name='тема')),
                ('text', models.TextField(verbose_name='тест обращения')),
                ('image', models.ImageField(blank=True, upload_to='feedback/screen', verbose_name='скриншот')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='users/resume')),
                ('job_title', models.CharField(max_length=300, verbose_name='должность')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1000, verbose_name='о себе')),
                ('skills', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=300, null=True, verbose_name='навыки')),
                ('min_price', models.SmallIntegerField(verbose_name='мин зарплата')),
                ('max_price', models.SmallIntegerField(verbose_name='макс зарплата')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('status_resume', models.CharField(choices=[('active', 'Активный'), ('archive', 'Архив')], default='active', max_length=300, verbose_name='статус вакансии')),
                ('experience', models.ManyToManyField(blank=True, to='core.experience', verbose_name='опыт работы')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Все резюме',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=300, verbose_name='должность')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1000, null=True, verbose_name='описание')),
                ('charge', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=2500, null=True, verbose_name='обязанности')),
                ('conditions', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='условия')),
                ('min_price', models.SmallIntegerField(verbose_name='мин зарплата')),
                ('max_price', models.SmallIntegerField(verbose_name='макс зарплата')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время публикации')),
                ('status_vacancy', models.CharField(choices=[('active', 'Активный'), ('archive', 'Архив')], max_length=300, verbose_name='статус вакансии')),
                ('required_experience', models.CharField(blank=True, max_length=1000, null=True, verbose_name='требуемый опыт')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='слаг')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacansies', to='core.category', verbose_name='Категория')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_vakancies', to=settings.AUTH_USER_MODEL, verbose_name='компания')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to='core.resume', verbose_name='отклики')),
                ('stack', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='стек технологий')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='responses',
            field=models.ManyToManyField(blank=True, to='core.vacancy', verbose_name='отклики'),
        ),
        migrations.AddField(
            model_name='resume',
            name='stack',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='стек технологий'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_resume', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
