# Generated by Django 4.2.5 on 2023-09-23 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_personfavorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ManyToManyField(blank=True, related_name='resume', to='core.resume', verbose_name='резюме')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_favorites', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
