# Generated by Django 4.2.5 on 2023-09-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyfavorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personfavorites',
            old_name='vacancies',
            new_name='vacancy',
        ),
    ]
